### ISSUE TITLE
表头筛选器，显示不出来

### ISSUE THREAD

**Issue by liyishi** [tccsg/dg-table#1]
您好，我下载了源码，在项目中能跑起来了，但是表头筛选器显示不出来，是什么原因？

**Comment by tccsg** [comment]
请问 控制台有报什么错误吗？

**Comment by tccsg** [comment]
@liyishi 请问 控制台有报什么错误吗？

**Comment by liyishi** [comment]
没有，我在页面F12检查元素看表头，筛选器完全没能注册上去。我在dg-table的mounted方法里看filterConfig是有测试模拟数据的

**Comment by tccsg** [comment]
@liyishi 那我这边检查一下 不过注册的筛选器不在表头下哦 他是跟el-table同一级的一个包装元素里面 对不起哈 最近事情比较多 今天才看到

**Comment by liyishi** [comment]
嗯，没事，能收到您的回复，我已经很高兴了。问题描述准确一点是表头的三角图标没能挂载上去，刚刚我把筛选器的v-show去掉，筛选器是可以显示出来的，不过都是堆在左上角

**Comment by tccsg** [comment]
@liyishi 你那边element-ui的包是2.4.11的吗？要最新的才可以哦，刚才试了降了下elementui的版本到2.3.9就出现你这种情况呢。

**Comment by liyishi** [comment]
@tccsg 我elementui版本是2.4.11，vue版本是2.5.10，但问题仍在，能加个微信看一下么？15768999672

**Comment by tccsg** [comment]
@liyishi 加了哦，你那边同意下。
