### ISSUE TITLE
fixed的表列不能旋转180°

### ISSUE THREAD

**Issue by ChinyChiu** [tccsg/dg-table#2]
![image](https://user-images.githubusercontent.com/18476698/63153911-08d40d00-c042-11e9-9319-dc8dd9d3df9b.png)

**Comment by tccsg** [comment]
你好，这个问题已经解决了哦，最新代码已经上传了。
![image](https://user-images.githubusercontent.com/32980934/63206507-193ec300-c0e8-11e9-87c5-d7ae8b621dc6.png)

**Comment by tccsg** [comment]
@ChinyChiu 你好，这个问题已经解决了哦，最新代码已经上传了。
![image](https://user-images.githubusercontent.com/32980934/63206507-193ec300-c0e8-11e9-87c5-d7ae8b621dc6.png)
