### ISSUE TITLE
table  @selection-change="handleSelectionChange" 赋值不成功，大佬

### ISSUE THREAD

**Issue by Mojie-Wang** [tccsg/dg-table#4]
vue 2.6.11 element-ui 2.8.2 
data() {
     multipleSelection: []
}
handleSelectionChange: function(val) {
     // this.multipleSelection = val;
    // console.log('---------------', val)
 }
this.multipleSelection赋值时不成功，而且当赋值时勾选框不能勾选

**Comment by tccsg** [comment]
@Mojie-Wang 有把multipleSelection绑定到视图层上面吗

**Comment by Mojie-Wang** [comment]
有的 需要判断multipleSelection.length的值

**Comment by tccsg** [comment]
@Mojie-Wang 这边修复了 如果是npm安装的最新版本是2.1.1 
用法上要注意的是
比如 
```js
:default-sort = "{prop: 'date', order: 'descending'}"
```  
不能这样写了

要写成：
```js
<dg-table :default-sort='ds'></dg-table>

data(){
  ...
  ds: {
    prop: 'date',
    order: 'descending'
  }
 ...
}
```

**Comment by Mojie-Wang** [comment]
谢谢，大佬
